### ISSUE TITLE
Undismissable ‘device is ignored temporarily’ notification

### ISSUE THREAD

**Issue by infusiastic** [pqrs-org/Karabiner-Elements#1844]
Background: I am using a 108-key external keyboard that rests on top of my laptop keyboard. Therefore in order to disable accidental presses I use ‘disable built-in keyboard when other keyboard’.
Problem: For some unobvious reasons ‘device is ignored temporarily’ notification often pops up. It is annoying in the first place because it requires pressing specific keys to dismiss and cannot be removed with the mouse swipe. But when my internal keyboard is disabled, I cannot dismiss it at all. Moreover, now it got stuck on ‘is ignored temporarily until eject key is pressed’ while my internal keyboard does not even have the eject key (I use a Macbook).

**Comment by tekezo** [comment]
Thank you for feedback!

> But when my internal keyboard is disabled, I cannot dismiss it at all. 

Karabiner-Elements enables the internal keyboard again while the notification window is shown on my machine.

Please show me your log messages in `Karabiner-Elements Preferences > Log` tab at this issue occurred again.

**Comment by j0hnsmith** [comment]
I'm seeing this too, I have a yubikey which I suspect is part of the problem.

**Comment by tekezo** [comment]
I succeed to reproduce this issue! (But the reproducibility is very low.)
This issue seems to occur if the key is released, and at the exact same moment Karabiner-Elements opens the device.

I fixed the problem at v12.4.2.
Please confirm the latest beta version.

How to upgrade to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>

**Comment by j0hnsmith** [comment]
I'm seeing this popup quite regularly for different keys. I've just installed the update, will let you know if I see it again.

**Comment by mladenny** [comment]
I’m using an Apple A1016 bluetooth keyboard and I’ve recently been having this issue too. I’ve just installed the v12.4.2 beta update and a few minutes after installing it, I got the notification in question.
[karabiner_log_2019-05-21T09-21-22.log](https://github.com/tekezo/Karabiner-Elements/files/3201052/karabiner_log_2019-05-21T09-21-22.log)

**Comment by tekezo** [comment]
@mladenny 

Thank you for feedback!

It's intended behavior that the alert is shown.
(It is necessary in order to avoid a key stuck issue due to macOS problem.)

The current problem is the alert is not hidden when you press the key again.
I guess your notification was hidden after pressing mute key again, as far as I see the log

Is my guess is right?
Or, was the alert undismissable?

**Comment by j0hnsmith** [comment]
I had an undismissable alert but not since I updated to the beta version.\

I only seem to get the alert when I type in my password after the computer is asleep (nearly every time), I'm wondering if a simple 200ms delay could prevent the popup from showing 95% of the time?

**Comment by mladenny** [comment]
@tekezo 

Yes, I could dismiss it by pressing the requested key, but the alerts were dismissable even before the update (see in the log: i had to press `Eject`, then `Mute`, before updating to v12.4.2). I’m just wondering why those alerts started showing in the first place. I think it started happening about two weeks ago, after I had to re-pair the keyboard, because macOS stopped seeing it. I don’t know if that helps.

**Comment by jaredmichaelwilliams** [comment]
@mladenny @tekezo im on A1016 as well, and i hit 'mute' and then 'eject' and the second i type anything on my keyboard it pops back up. im also on 12.4.2 beta. Currently causing karabiner not to work with my keyboard

**Comment by jaredmichaelwilliams** [comment]
https://github.com/tekezo/Karabiner-Elements/blob/b7bee05fbf5252edbcb43cf383403e866d298c14/src/core/grabber/include/device_grabber.hpp#L619-L638

**Comment by LvChengbin** [comment]
It might be a really bad feature and troubled me a lot. Can I switch it off from somewhere?

**Comment by KevinVerre** [comment]
@tekezo I am also having an issue like this. One of my laptop keys is broken. To workaround it, I set up my Karabiner-elements to completely ignore that key in case it gets stuck. And I have remapped a different key to replace it. But then this message comes up "....ignored temporarily until key_code: e is pressed again. But e is the key that doesn't work. So I can't dismiss the notification and get my key remappings turned on again

**Comment by sursh** [comment]
I'm also getting this pop up only after typing my password after the computer wakes, just like @j0hnsmith, and like others, I've only started getting it recently (like in the last few days)

Pressing the keys in the error message doesn't really seem to help, but the message does eventually go away. (Also it's hard to tell what key to press sometimes, especially since they're lowercase in the error message but uppercase on the keyboard, so it's hard to differentiate between l and | and I)

**Comment by Nek** [comment]
I'm having the same issue. Restarting karabiner_grabber helps: ```sudo killall karabiner_grabber```.

**Comment by infusiastic** [comment]
After the latest update the problem still exists. Had to downgrade to 12.3.0.

**Comment by AAverin** [comment]
Don't remember updating carabiner recently, but just started getting this.
I have 4 keyboards that I switch between, and all external keyboard are supposed to disable internal MAC keyboard

**Comment by nebular** [comment]
Happens for me with latest 12.5.0 and 12.5.3 everytime I press CAPS-LOCK. I was using an old version that just fixed the CapsLock key (can't remember number) and I never had this problem!

`2019-07-26 20:53:29.576] [info] [grabber] Keyboard (device_id:4294968135) is ungrabbed.
[2019-07-26 20:53:40.212] [warning] [grabber] Keyboard (device_id:4294968135) is ignored temporarily until {"key_code":"caps_lock"} is pressed again.
[2019-07-26 20:54:07.915] [info] [grabber] Keyboard (device_id:4294968135) is grabbed.
[2019-07-26 20:55:00.379] [warning] [grabber] Keyboard (device_id:4294968135) is ignored temporarily until {"key_code":"caps_lock"} is pressed again.
[2019-07-26 20:55:00.391] [info] [grabber] Keyboard (device_id:4294968135) is ungrabbed.
[2019-07-26 20:55:01.296] [warning] [grabber] Keyboard (device_id:4294968135) is ignored temporarily until {"key_code":"caps_lock"} is pressed again.
`

**Comment by shukebeta** [comment]
Due to a few keys not working good, I am using a cheap Bluetooth keyboard that rests on my Macbook keyboard too. It is very convenient if all is good. However, I have met a similar problem. It only works for several minutes, then the Bluetooth keyboard stop work. You just said you have to downgrade to 12.3.0, and I found that 12.3.0 don't have the feature that can disable the built-in keyboard. How do you resolve this problem?@infusiastic

**Comment by infusiastic** [comment]
It can be done in the Devices tab.
![image](https://user-images.githubusercontent.com/5081164/62817831-7a5a1a00-bb6f-11e9-881e-d82c88f8bb84.png)

**Comment by frumbert** [comment]
![Screen Shot 2019-09-08 at 2 11 20 pm](https://user-images.githubusercontent.com/592257/64483306-bd78dd00-d242-11e9-89fe-42eaedf99329.png)

I have this appearing when it detects me connecting my external keyboard, sleep, then wake the machine. The message is always on top including in full screen.

My issue is that it prompts me to press the very key that is BROKEN on my macbook so I can't press it. Is there a way to disable this notification altogether?

**Comment by chrisgross** [comment]
I get this notification after working from home and coming into work and connecting my MacBook to my Thunderbolt display, to which my wired keyboard is attached. The real problem is, this causes my keyboard to be completely disabled until the notification gets unburied from beneath other windows and I finally see it. I've never enabled this feature so I really wish this would stop.

**Comment by LazaroFilm** [comment]
Still having this issue here with a Bluetooth Keychron K2 keyboard. It's really annoying. This might have to do with the fact that the keyboard goes to sleep every 10 min of inactivity.

**Comment by robbwh** [comment]
Also still having this issue. Would just be nice if the notification were dismissable.

**Comment by jbender0** [comment]
I'm having the same issue as others. I'm using this app because one of the keys on my keyboard is broken and seems to be in a constantly "pressed" state. So I've mapped that button to a virtual "nothing". However, the popup is a real PITA and makes a lot of other apps unusable since it takes up important real estate on the screen. You can easily replicate the issue by holding onto any key you wish when starting up the app - in most of the cases of the above commenters (and me), one of our keys is broken - that's why it's hard for the developer to test this.

**Comment by leofontes** [comment]
Still seeing the issue, whenever I wake up the macbook I need to quit Karabiner and launch again to get it removed :/

**Comment by virajhesh** [comment]
> @tekezo I am also having an issue like this. One of my laptop keys is broken. To workaround it, I set up my Karabiner-elements to completely ignore that key in case it gets stuck. And I have remapped a different key to replace it. But then this message comes up "....ignored temporarily until key_code: e is pressed again. But e is the key that doesn't work. So I can't dismiss the notification and get my key remappings turned on again

i have same issue. Wanna answer

**Comment by vogler** [comment]
<img width="417" alt="image" src="https://github.com/pqrs-org/Karabiner-Elements/assets/493741/d8f967ef-c3d0-4c65-880e-e8f666022bed">

I wake my MacBook from sleep by pressing CMD (same problem with ALT), but then often get this notification on both of my displays which I then have to close manually 😞
How can I avoid this?

**Comment by tarikkavaz** [comment]
> <img alt="image" width="417" src="https://user-images.githubusercontent.com/493741/258580429-d8f967ef-c3d0-4c65-880e-e8f666022bed.png">
> I wake my MacBook from sleep by pressing CMD (same problem with ALT), but then often get this notification on both of my displays which I then have to close manually 😞 How can I avoid this?

+1

**Comment by LazaroFilm** [comment]
The only thing you can do is press the key again for karabiner to detect the state of the key properly.

**Comment by vogler** [comment]
@LazaroFilm That somehow doesn't always work for me.

**Comment by LazaroFilm** [comment]
Make sure you're pressing the right key. Sometimes it asks for another key for you to press.

**Comment by samtuke** [comment]
This is the problem dialogue in my case
![2023-10-31_23-16](https://github.com/pqrs-org/Karabiner-Elements/assets/695422/69dd6265-dffd-4319-8292-fe13bd1342ef)

**Comment by PierBover** [comment]
I'm seeing this every time I wake up my MBP on all my monitors.

I press the key multiple times and the alert doesn't go away.

Isn't there a way to disable this useless notification?
