### ISSUE TITLE
[Feature Request] Port to Linux

### ISSUE THREAD

**Issue by a-b** [pqrs-org/Karabiner-Elements#1936]
Recently I had to switch to the Linux workstation. This is the only app I’m missing.

**Comment by dragon788** [comment]
It would basically require a rewrite of the entire application to support Linux because it deals with keyboards and input in a completely different manner.

How the input is handled also depends greatly on which window manager you are using, Gnome, KDE, i3, etc. Your best bet is to check on Stack Overflow for the keys/behaviors you want to remap/create and learn how to do it for Linux and the window manager you are using.

**Comment by a-b** [comment]
Simple remapping is not sufficient for my needs. I'm interested in more complex behavior mapping, like mouse emulation etc.
