### ISSUE TITLE
Severe issues with Function keys in Sublime Text 3 (MB Pro with Touch Bar)

### ISSUE THREAD

**Issue by gemisigo** [pqrs-org/Karabiner-Elements#1972]
macOS version: Mojave 10.14.6
Karabiner-Elements version: 12.6.0

Active Karabiner-Elements causes serious problems with Function keys. There are several actions that are bound to different modifier + function key combinations, eg. super+f2 to toggle bookmark, shift+f2 for jumping to the previous bookmark, etc. None of those are working as expected when Karabiner is active. Each of those combinations is recognized as if no modifiers were pressed.

**Comment by dagguh** [comment]
Got the same problem.
With Karabiner SHIFT+Fn+F6 is treated as Fn+F6. It completely messes up my IDE hotkeys.

**Comment by max-xk** [comment]
macOS version: Mojave 10.14.5
Karabiner-Elements version: 12.7.0
Device: MacBook Pro 2019 with touch bar
In "MacOS Settings -> Keyboard -> Touch Bar shows" I have an option "F1, F2, etc."

The same problem in IDEs like Webstorm: function keys are not triggered together with other modifiers like command button, if karabiner is running.
Karabiner-EventViewer displayed function keys with no previously held modifiers (with and without karabiner running).

In "MacOS Settings -> Keyboard -> Touch Bar shows" I have an option "F1, F2, etc."

This issue is kind of blocker for developers, who are using karabiner and hot key combinations with function keys (i.e. almost all developers who are using karabiner 😄).

@tekezo Are there any plans to address somehow the blocker in future releases (or at least to propose some workaround)?

**Comment by dagguh** [comment]
Still present in Karabiner 12.8.0 and macOS 10.15.1

**Comment by bealex** [comment]
I’ve got this too.

**Comment by nriley** [comment]
I was able to partially work around this using a utility I built for another purpose (https://github.com/nriley/Karabiner-Elements-App-Profiles).  This utility will automatically switch to a different Karabiner profile when a particular app is frontmost.

Because I only need to use Shift-function keys in one app (Terminal), I added a profile named "com.apple.Terminal":

<img width="930" alt="image" src="https://user-images.githubusercontent.com/68303/72222795-cc480700-3536-11ea-9778-5cbf599c7627.png">

In this profile I disabled the internal keyboard:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/68303/72222808-dcf87d00-3536-11ea-880e-c80a970affef.png">

This turns off Karabiner in Terminal, letting me use Shift-function keys.  Unfortunately I was using Karabiner to map right Option to Insert in Terminal; I will have to do without it for now.  Hopefully this issue can be addressed soon!

**Comment by IanEdington** [comment]
This seems to be be the same issue as #460 

It doesn't look like anyone's going to fix this

**Comment by gemisigo** [comment]
> This seems to be be the same issue as #460
> 
> It doesn't look like anyone's going to fix this

While they may be related and might even have a common cause, this one and #460 are not quite the same. 

The poster of that issue complains about the Fn key not switching the Touch Bar from _Expanded Control Strip_ to _Show App Controls_. I have my Touch Bar set to show _Quick Action_ and _Show Fx keys_ when Fn is pressed. My Fn works exactly as expected, it switches to Function keys when pressed. The problem is that when Karabiner is running, pressing a Function key disregards every possible modifier combinations. It behaves as if a single Fx key was pressed.

**Comment by gemisigo** [comment]
Well, this is sad… ☹️

**Comment by nriley** [comment]
This seems to be an actively maintained project. This seems like a serious bug which has been present for at least 6 months. I don’t really understand the point of closing bugs that haven’t been fixed.

**Comment by nriley** [comment]
Never mind — this is not a bug, just a poorly documented/exposed feature!

See https://github.com/pqrs-org/Karabiner-Elements/issues/2201#issuecomment-610990146. You need to enable Karabiner-Elements on the Touch Bar “keyboard” which appears as “No product name (No manufacturer name)”.  Once I did this, I was able to use modified function keys in the Touch Bar!  No more workaround needed.

**Comment by gemisigo** [comment]
> You need to enable Karabiner-Elements on the Touch Bar “keyboard” which appears as “No product name (No manufacturer name)”. 

I wouldn't have ever guessed that the Touch Bar was hiding under the alias "No product name". I always thought that one was some miserable remnant of the external keyboard I used in the past. Anyway, it works now and I hope everyone having the same problem runs into your comment (or #2201, whichever they find first). 
This issue is already closed. @nriley, @huylv, thank you both! 👍
