### ISSUE TITLE
Control + left mouse click instead of command + left click?

### ISSUE THREAD

**Issue by iwebsguy** [pqrs-org/Karabiner-Elements#2000]
In Windows you press control + left click (currently right clicks) to select multiple items, I have not figured out a way to get this working. I have a simple rule already setup to replace the fn and left_command key on my MacBook along with a number of the "PC-Style" advanced rules but can't find an advanced rule to do control+click instead of command+click.

**Comment by serdarsen** [comment]
I'm looking to remap Control-click to Command-click in order to open links in a new tab using Control and the left mouse button. Unfortunately, the current configuration doesn't seem to be working as expected. Could someone please assist in fixing the script provided below?

```json
{
  "title": "Finder and system shortcuts",
  "rules": [
    {
      "description": "Control-click to Command-click",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button1",
            "modifiers": {
              "mandatory": [
                "left_control"
              ]
            }
          },
          "to": [
            {
              "pointing_button": "button1",
              "modifiers": [
                "left_command"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

I appreciate any assistance in making this remapping work as intended. Thank you!
