### ISSUE TITLE
karabiner_session_monitor affects hover on websites

### ISSUE THREAD

**Issue by dawidadach** [pqrs-org/Karabiner-Elements#2003]
I am facing a strange behaviour, after starting my Mac, non of the hover effect in the browser works correctly regardless of the web browser (same for Chrome Version 77.0.3865.90 (Official Build) (64-bit) as well as newest Safari or Firefox).

I.e. when I open my bank website there should be new buttons appearing when I hover mouse over my account number but nothin happens. Or i.e. this website https://mdbootstrap.com/docs/jquery/css/hover-effects/ , when you howev over examples they are chaning (color, mask etc).  However it doesn't work for me. 

I tried debuging, first I checked incognito mode (all extensions off) but it didn't help. Then I started to kill other application one by one and I finally found that when I kill **karabiner_session_monitor** proces in activity monitor everything backs to normal. 

I have 12.7.0 version

**Comment by tekezo** [comment]
I cannot reproduce this issue.
As far as  I read your description, I guess this issue is caused by macOS API problem which karabiner_session_monitor uses.

Does this issue always happen you use web browsers?

**Comment by dawidadach** [comment]
I found something new. 

Apparently it's not caused by process itself. I just found that this i combination of my mouse (Logitech MX Anywhere 2) and Karabiner. As soon as I eject mouse receiver it works like a charm. 

When I attach it again hover stops working. But when I kill Karabiner everything works like a charm again. 

Recently I start getting some strange notification window from Karabiner which I could close. It happened when my Mac was running out of battery, going sleep and after restoring this popup occured. I can't recall error exactly but I will try to reproduce.

**Comment by samfearn** [comment]
Hi,

I have a similar problem, except the hover issue affects the OS as a whole, not just web browsers.

If KE is not running, then the OS does not recognise the hover location of my mouse. One obvious effect is that the dock will appear when I move my mouse to the bottom edge of the screen, but as I move my mouse across the dock, the name stays above the location where I first moved the mouse into the dock:

![2019-10-18 10 14 46](https://user-images.githubusercontent.com/2106074/67082075-50852b00-f190-11e9-96de-6e0af337b9aa.gif)

Clearly this isn't a KE problem (I think it's due to the drivers being old and updates not existing and they used to be installed in the system library somewhere, so Catalina removed them), since starting KE fixes the problem. **However**, if KE is running when I plug the mouse in, then the problem persists until KE is restarted. Since my mouse is plugged into a dock on my desk, this means restarting KE every time I get back to my desk.

**Comment by dawidadach** [comment]
Any idea how to solve that?

**Comment by dawidadach** [comment]
Well issue still persist therefore I wouldn't close it yet.

**Comment by samfearn** [comment]
This shouldn't be closed, it's an ongoing problem

**Comment by ianhyzy** [comment]
This is still happening for me, restarting KB seems to fix it
