### ISSUE TITLE
Allow prompt not showing

### ISSUE THREAD

**Issue by ganti324** [pqrs-org/Karabiner-Elements#2016]
os: mac os x catalina (released today)
karabiner version: 12.7.0(latest as of today)

In system preferences > security and privacy> 

the prompt to allow is not showing

**Comment by christo-ph** [comment]
Hi @ganti324 

to allow what exactly? If you mean the input monitoring, go to system settings -> security -> privacy and enable grabber and observer:

![image](https://user-images.githubusercontent.com/16965068/66459545-87af5a00-ea75-11e9-8043-65922a305d4f.png)

**Comment by ganti324** [comment]
![image](https://user-images.githubusercontent.com/11367683/66509452-ed0c4680-ea87-11e9-904e-1264586e5175.png)

Talking about this prompt

**Comment by ganti324** [comment]
![image](https://user-images.githubusercontent.com/11367683/66509495-0a411500-ea88-11e9-9dd2-e7f3cba9fbda.png)

Doesn't show here

**Comment by ganti324** [comment]
![image](https://user-images.githubusercontent.com/11367683/66510167-5771b680-ea89-11e9-8f24-85794c88b611.png)

Doesn't show even after unlocking

**Comment by ganti324** [comment]
![image](https://user-images.githubusercontent.com/11367683/66514243-96a40580-ea91-11e9-9d11-a835962b3690.png)

Input monitoring has been enabled as shown above. 

But karbiner key mapping doesn't work probably because of the problem above (The prompt to allow karabiner doesn't even show for me to allow it)

**Comment by misterpyrrhuloxia** [comment]
@ganti324, I'm seeing all of these same issues EXACTLY as you are.

**Comment by tekezo** [comment]
It might be caused by corrupted system cache of macOS.

Try to restart your Mac in safe mode in order to refresh macOS system caches.
Then, I believe you can see the button after restart in normal mode.
(Press and hold the Shift key at boot)
https://support.apple.com/en-us/HT201262

Note:
Safe mode boot takes a long time (~ 10 min) if you enabled Time Machine because safe mode checks all Time Machine snapshots.
Please do it with time to spare.

**Comment by ganti324** [comment]
I tried that but it didn't work.

**Comment by ganti324** [comment]
Help me! Please! I am addicted to Karabiner!

**Comment by misterpyrrhuloxia** [comment]
> It might be caused by corrupted system cache of macOS.
> 
> Try to restart your Mac in safe mode in order to refresh macOS system caches.
> Then, I believe you can see the button after restart in normal mode.
> (Press and hold the Shift key at boot)
> https://support.apple.com/en-us/HT201262
> 
> Note:
> Safe mode boot takes a long time (~ 10 min) if you enabled Time Machine because safe mode checks all Time Machine snapshots.
> Please do it with time to spare.

Well that solved it for me. Thanks!!

**Comment by tekezo** [comment]
@ganti324 
Does reinstalling Karabiner-Elements solve your issue?

**Comment by ganti324** [comment]
Nope. still have the same problem

**Comment by JacobSyndeo** [comment]
<img width="1609" alt="Screen Shot 2019-10-11 at 1 31 24 PM" src="https://user-images.githubusercontent.com/1004637/66679471-7c9e2a80-ec2b-11e9-96bb-f9428317817c.png">
<img width="636" alt="Screen Shot 2019-10-11 at 1 32 10 PM" src="https://user-images.githubusercontent.com/1004637/66679493-8a53b000-ec2b-11e9-95ea-f78a71c07974.png">
Similar issue here. No prompts to allow access.

**Comment by cyn110** [comment]
Same issue here. I'm on Mojave (10.14.6), and I don't have Input Monitoring in Privacy setting.

**Comment by JacobSyndeo** [comment]
@cyn110 I *think* Input Monitoring is new in Catalina.

**Comment by zcramos** [comment]
Having the same issue :(

**Comment by roblebel** [comment]
+1, Mojave (10.14.6)

**Comment by menathan** [comment]
Same issue

**Comment by Mastergalen** [comment]
Same issue on MacOS Catalina `10.15.5 `

Karabiner-Elements version: `12.9.0`

**Comment by pelmered** [comment]
I had the same problem. It turns out that I had missed this promt just before:
<img width="465" alt="Screenshot 2021-11-17 at 15 06 11" src="https://user-images.githubusercontent.com/680058/142216495-7b473949-dcd4-4fdf-8e24-dd8272c6eaed.png">
 
When I click "Open System Preferences" there I got to right place with both `karabiner_grabber` and `karabiner_observer` in the list.  

Hope that helps somebody.

I'm on macOS Monterey `12.0` and Karabiner `14.2.0`
