### ISSUE TITLE
Karabiner-Elements crashes OSX WindowServer

### ISSUE THREAD

**Issue by christo-ph** [pqrs-org/Karabiner-Elements#2017]
OSX Catalina 10.15
Karabiner 12.7 (&12.7.2)
MBP15 2018

As soon as I open Karabiner Elements for the first time, it asks for Permissions for karabiner_grabber and karabiner_observer. While I have not checked them, everything works fine. As soon as I check them and press the first key (any key), the OSX WindowService crashes and I am thrown to the login screen.

When I login again while the permission are still set, I crashes all the time and throws me back once again to the login screen.

I have to start OSX in safe mode to disable the permission. (For that I created #2015 - would be easier)

While I could not find anything in the karabiner logs (`~/.local/share/karabiner/log`)

Though I could find crash reports in OSX console for every single 'logout':

```
Process:               WindowServer [281]
Path:                  /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer
Identifier:            WindowServer
Version:               600.00 (440.7.10)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
Responsible:           WindowServer [281]
User ID:               XX

Date/Time:             2019-10-08 19:31:50.115 +0200
OS Version:            Mac OS X 10.15 (19A583)
Report Version:        12
Bridge OS Version:     4.0 (17P572)
Anonymous UUID:        XXXXXXX-XXXX-XXXX-F810-AC5EE2F63BF2

Sleep/Wake UUID:       1326EE06-3A94-4D6D-9102-D1B14BB03B4F

Time Awake Since Boot: 950 seconds
Time Since Wake:       290 seconds

System Integrity Protection: enabled

Crashed Thread:        5  Dispatch queue: com.apple.WindowServer.HIDEvents

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString _getValue:forType:]: unrecognized selector sent to instance 0x7f92af5506a0'
StartTime:2019-10-08 14:19:23
GPU:IG&AMD

```

On my MacBook Air 2018 this does not happen with the same software versions for karabiner and OSX.

**Comment by ricklupton** [comment]
I have seen a similar error. It seems to be triggered by plugging/unplugging external USB keyboards, but I cannot reliably reproduce it at the moment.

The WindowServer repeatedly crashes and restarts for a while (giving a flashing and unresponsive screen) before eventually giving up and returning to the login screen.

**Comment by jsrozner** [comment]
I am observing frequent GUI crashes in catlina 10.15.5.

They are triggered by using mission control. Karabiner is the only third party kext that is loaded. I do not experience crashes in safe mode when Karabiner kext is not loaded.

**Comment by ricklupton** [comment]
@tekezo this is still happening regularly with the latest version. Is there anything we can do to provide more information that would help?

**Comment by jsrozner** [comment]
The crashes I was observing were on a brand new 2020 Macbook pro 13". I returned that computer and went back to my 2013 Macbook air.

I also made some tweaks to my own karabiner setup around the same time. It previously had issues with the caps lock remap I think. Since making tweaks I have not experienced any crashes and my slate window movements (pinning windows to left/right /full screen, or moving them by a monitor) have been much snappier. Here's my [karabiner config ](https://github.com/jsrozner/dotfiles/blob/master/other_config/karabiner/karabiner.json)
I now have
- caps lock -> escape on tap, control on hold
- left control -> caps lock on tap, hyper on hold

Even before the new mac, I would sometimes have to kill karabiner to / restart the computer to get control of my computer back. Since the change away from caps lock I haven't had to do that even once.

I also 
- set up displays to *not* have separate spaces (system pref > mission control)
- system pref > accessibility> displays: reduce motion, reduce transparency
- disabled GPU acceleration on chrome (I think this was more an issue with the brand new macs)

I'm still on 10.15.7
