### ISSUE TITLE
Mailing List?  Build security?

### ISSUE THREAD

**Issue by nickpapadonis** [pqrs-org/Karabiner-Elements#2045]
Is there a mailing list or forum to discuss Karabiner Elements?

I ask because I'm trying to remap the iMac Bluetooth keyboard to a LISP machine, Symbolics Space Cadet or Knight keyboard.

I also have questions on build security and how to be sure there is no key logger included in the build.

Appreciate your guidance.

Thanks

**Comment by tekezo** [comment]
There is a discussion about security of the released binary.
https://github.com/pqrs-org/Karabiner-Elements/issues/1684

## Summary

- If you doubt the released binary, Karabiner-Elements is open source software, so you can build it from source code.
- But, due to macOS kext signature requirements, the signed pre-built kext (Karabiner-VIrtualDevice) is embed even if you build Karabiner-Elements from source code.
- If you joined Apple developer Program, you can get a power to sign the kext by requesting to Apple.
  <https://developer.apple.com/library/archive/documentation/Security/Conceptual/System_Integrity_Protection_Guide/KernelExtensions/KernelExtensions.html>
- After you get Developer ID Certificate, you can build Karabiner-Elements without pre-built binary by the following steps.
  <https://github.com/pqrs-org/Karabiner-Elements#how-to-build>
- I'm working about automated build to ensure the released binary is generated from the published source code, but it's not available yet.

**Comment by tekezo** [comment]
Note:
Apple introduced DriverKit since macOS Catalina.
You may possibly replace the virtual keyboard device by DriverKit that is not require kext.
If the modification is achieved, we can build Karabiner-Elements without Developer ID Certificate.
(== We don't need to use kext for virtual device.)

**Comment by tekezo** [comment]
Note:
If you need only a simple modification, Apple provides another way.
https://developer.apple.com/library/archive/technotes/tn2450/_index.html
 (But, I don't know whether the Apple way works on the latest macOS.)

**Comment by nickpapadonis** [comment]
Thanks.  This is my understanding with additional question for Karabiner team.

Apple Mac OSX key mapping interface for 10.12: It appears two methods are available and have questions for Karabiner team.  The script using “hidutil property —set ‘{“UserKeyMapping”:[{HIDKeyboardModifierMappingSrc: 0xHIDSRC, “HIDKeyboardModifierMappingDst”: 0xHIDDST, …}.  There is also a programatic method using Objective-C.  Both methods use the HID keyboards usage IDs in the “Key Table Usage” as offsets from base address 0x700000000.  This base indexes the table in the USB consortium document (https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf).

Has Karabiner considered using this interface?  How is Karabiner performing remapping now?  Does it add a device driver to intercept these code and modify outside above interface?

Also appreciate any feedback from someone that has tested if this interface still works in latest macOS.

Thank you

**Comment by nickpapadonis** [comment]
Do you know how to easily find the mapping of keycodes on Page 53 of this document to physical iMac Bluetooth Keyboard keys?  I.e. other then trial and error, for instance pressing a key and capturing the keycode event?

> https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf <https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf>
Thanks again

**Comment by nickpapadonis** [comment]
I see there is a hidden menu when pressing SHIFT-OPTION on the Bluetooth Icon on the top of the screen dialog.  It has an option for DEBUG.  This page details:

https://www.macobserver.com/tmo/article/os-x-bluetooth-menu-reset-devices

My version is missing “enable bluetooth logging” , which I would assume log the keypress.

Anyone know how to log the Bluetooth HID keypresses keycodes?

Thanks

**Comment by tekezo** [comment]
Karabiner-Elements does not use the `hidutil property` way.
Karabiner-Elements grabs key events by own iokit daemon and modify them.

Please use Apple forum about generic hidutil questions.

If you use Karabiner-Elements, you can use EventViewer to investigate the input events.
https://pqrs.org/osx/karabiner/document.html#eventviewer
And you can modify them by simple modifications.
https://pqrs.org/osx/karabiner/document.html#configuration-simple-modifications
You can also use more complex modifications.
https://pqrs.org/osx/karabiner/document.html#configuration-complex-modifications
