### ISSUE TITLE
Remapping "keycode 207?"

### ISSUE THREAD

**Issue by Jont828** [pqrs-org/Karabiner-Elements#2101]
I have a Menu key on my PC keyboard that I'm using with my mac, but when I pull up event viewer, it registers the press with code 207 and name as (number: 207). Since that key doesn't appear to do anything, I'd like to remap it on my Mac. How should I remap it? It doesn't appear to show under the simple mods. I'm thinking about using complex mods, but I'm not sure how to target the key since it's not a normal keycode.

**Comment by tekezo** [comment]
Thank you for contact!

Since Karabiner-Elements v12.8.3 (the latest beta version), you can add simple modifications for unnamed keys from `Add xxx to Karabiner-Elements` button on EventViewer.
Please confirm the latest beta version.

How to upgrade Karabiner-Elements to the latest beta version:
<https://pqrs.org/osx/karabiner/document.html#check-for-updates>


If you want to create complex modification, you can specify key by raw number as follows.
https://pqrs.org/osx/karabiner/json.html#raw-number-key-code
