### ISSUE TITLE
Shift + F7 does not work in Matlab when Karabiner-Elements is running

### ISSUE THREAD

**Issue by xiao-zang** [pqrs-org/Karabiner-Elements#2106]
In Matlab the keyboard shortcut for "Evaluate Selection" is Shift + F7. In my MacBook Pro with Touch Bar (function keys appear on the Touch Bar when pressing Fn), it is effectively Fn + Shift + F7. However, when the Karabiner-Elements is running even with an empty profile (no key modification), Fn + Shift + F7 does not trigger "Evaluate Selection". After I quit Karabiner-Elements, the same key combination works again. Do you have any suggestion about what might be the rationale behind such behavior?

Thanks and Happy New Year!

**Comment by nriley** [comment]
I am having the same problem — if I press Shift-F7 (on the Touch Bar) when Karabiner-Elements is running it sends F7 rather than Shift-F7. If I quit Karabiner-Elements, it sends Shift-F7. I use software that uses the F-keys on a VT220 keyboard frequently (e.g. Shift-F5 = F15/Help, Shift-F7 = F17). Can I fix this with configuration or is it a bug?

**Comment by nriley** [comment]
@xiao-zang — I resurrected an old utility of mine as a workaround; details [here](https://github.com/pqrs-org/Karabiner-Elements/issues/1972#issuecomment-573437842). If you don't use Karabiner in Matlab otherwise it might be workable for you.

**Comment by xiao-zang** [comment]
@nriley For now I changed the keyboard shortcut in Matlab preference to something not relying on function keys. Thank you for your solution anyway!

**Comment by IanEdington** [comment]
should this be closed in favour of #1972?
