### ISSUE TITLE
How to remap non english keys like ñ or ç or ¡

### ISSUE THREAD

**Issue by JavierRSobrino** [pqrs-org/Karabiner-Elements#2159]
I have an spanish ISO keyboard and keys like ñ, ç, ¡ don't appear in the Simple Modifications tab. How to make them appear there?

**Comment by marlonrichert** [comment]
Karabiner-Elements always uses the US ANSI names for the keys on your keyboard, no matter what language your keyboard is. You can use the EventViewer to find out what "Name" your key actually has to KE. For more info, see https://github.com/pqrs-org/Karabiner-Elements/issues/2228#issuecomment-615119061

**Comment by niilz** [comment]
I have the same issue with my German keyboard layout.
I am trying to map umlaut character ```ö, ä``` to brackets ```[]```.
If I use the Event Viewer ```ö``` gives ```semicolon (;) 51```
If I now map ```semicolon``` to ```open-bracket``` I am getting a ```+```.
Is there a better way to figure out the actual mapping, then try and error?

**Comment by marlonrichert** [comment]
@niilz There isn't a dedicated `[` key on a German keyboard, so you cannot use Karabiner to map to it either, unfortunately.

You have two options to fix this:
* Go to System Preferences > Keyboard > Input Sources and select a layout that does have dedicated `[]` keys instead of a German layout.
  <img width="780" alt="image" src="https://user-images.githubusercontent.com/644725/80974091-ee88cc00-8e28-11ea-85da-038d3e5a3eed.png">
* Use [Ukelele](https://software.sil.org/ukelele/) to create a custom keyboard layout, which you then select in the same way.

**Comment by niilz** [comment]
@marlonrichert Thank you for the response and the two options. That is very helpful.
It's quite unfortunate that the OS doesn't provide a bit more flexibility. But that's a total different discussion.
I now know where to look for, so that's a great start. 👍
