### ISSUE TITLE
Show desktop Media Keys action is missing in Simple Modifications

### ISSUE THREAD

**Issue by leancode** [pqrs-org/Karabiner-Elements#2181]
The Show Desktop action is missing in the dropdown in simple modifications. There is no way to assign a key to show the desktop (at least not known to me). I think it simply got forgotten.
![Screenshot 2020-03-09 at 10 37 01](https://user-images.githubusercontent.com/611460/76200715-64d6cc80-61f2-11ea-9883-a4f54704be86.jpg)

**Comment by marlonrichert** [comment]
⌘ + mission control = show desktop

You cannot do this directly with simple modification; you'd need a complex modification for that. 

However, instead of using KE for this, you can just assign a keyboard shortcut to Show Desktop directly in System Preferences:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/644725/79759011-ce381800-8326-11ea-9e3e-5f00b248779c.png">
