### ISSUE TITLE
Can't prevent Karabiner-Elements from starting at boot

### ISSUE THREAD

**Issue by jmyz0455** [pqrs-org/Karabiner-Elements#2207]
I can't prevent Karabiner-Elements from starting when the system boots. I can't find the Karabiner-Elements option in "System Preferences-Users & Groups-Admin-Login Items". I don't know why Karabiner-Elements can still be opened automatically when I log in.

I feel disturbed. My system version is macOS 10.15.4 and Karabiner-Elements version is 12.9.0. I tried uninstalling Karabiner-Elements and installing it again, and the problem remains the same. 

I found [issue195](https://github.com/pqrs-org/Karabiner-Elements/issues/195) but it didn't work for me. Hope someone can tell me how to cancel launch Karabiner-Elements at login. I don't like software that startup automatically without my permission.

**Comment by tekezo** [comment]
Quit Karabiner-Elements.
https://karabiner-elements.pqrs.org/docs/manual/operation/quit/

After quit, Karabiner-Elements will not start at boot.

**Comment by jmyz0455** [comment]
> After quit, Karabiner-Elements will not start at boot.

Thank you very much.

**Comment by AlftheElf** [comment]
I just was to clarify something because I quit the program but it still showed up on reboot.
You have to also remove 'Karabiner Elements' from the login items list at Settings > Users & Groups > Login Items.
Use the minus button to remove it from the list completely. Even if 'hidden' is selected, it still shows up again. 🦄
