### ISSUE TITLE
Binding a key sequence executed within a certain time interval to another key

### ISSUE THREAD

**Issue by man-goat** [pqrs-org/Karabiner-Elements#2269]
My mouse has the unfortunate habit of firing twice occasionally. Is there a way to bind all double clicks within a certain interval to a single mouse click?

**Comment by thoelze1** [comment]
You could use `set_variable` on a mouse click to set a variable indicating that the mouse was recently pressed, and that additional presses should temporarily be ignored. You can use `to_delayed_action` to then unset that variable after a desired number of milliseconds (which can be specified with `to_delayed_action_delay_milliseconds`) have passed since the initial click. See the [`set-variable` documentation](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/set-variable/) and the [`to_delayed_action` documentation](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-delayed-action/).
