### ISSUE TITLE
Is it possible to enable rules only for specific keyboard layout (karabiner)?

### ISSUE THREAD

**Issue by avatar-lavventura** [pqrs-org/Karabiner-Elements#2272]
On Karabiner I am enabling multiples rules under its complex modifications setup, such as `Emacs key bindings`.

I was wondering is it possible to use those enables rules only for a specific keyboard layout such as `U.S.` and automatically disable those rules when I switch to an another keyboard layout.

Link: https://stackoverflow.com/q/60329520/2402577

**Comment by thoelze1** [comment]
Take a look at the [`device_if` example](https://ke-complex-modifications.pqrs.org/example.html) and the [`Conditions` documentation](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/)

**Comment by avatar-lavventura** [comment]
On my end actually I just want to disable `Swap {} and []` when I am using Turkish keyboard but enable it when I am using `U.S.` keyboard.

I couldn't find the code for the examples on the first link. On which file should I make the changes?

**Comment by thoelze1** [comment]
So you have a rule called `Swap {} and []`? How did you add it?

**Comment by avatar-lavventura** [comment]
Usıng import with the help of this answer: ( https://stackoverflow.com/a/60286402/2402577 ). Like for coding I us U.S. keyboard but if I switch to different languagle it makes swapped characters capital

**Comment by thoelze1** [comment]
If you imported the rule, then it is saved as a json file in `~/.config/karabiner/assets/complex_modifications/`, as something like `~/.config/karabiner/assets/complex_modifications/1589318523.json`. This json file stores the rules as elements in `manipulators`. To each of these `manipulators` elements, you need to add a `conditions` item that checks what language your keyboard is. I think you should use [`input_source_if`](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/input-source/) for this. 

So the original file looks like this:

```
{
  "description": "Swap {} and []",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "open_bracket"
      },
      "to": [
        {
          "modifiers": ["left_shift"],
          "key_code": "open_bracket"
        }
      ]
    },
    ...
}
```

You should modify each of the `manipulators` so it looks something like this:

```
{
  "description": "Swap {} and []",
  "manipulators": [
    {
      "type": "basic",
      "conditions": [
        {
          "type": "input_source_if",
          "input_sources": [
            {
              "language": "en"
            }
          ]
        }
      ], 
      "from": {
        "key_code": "open_bracket"
      },
      "to": [
        {
          "modifiers": ["left_shift"],
          "key_code": "open_bracket"
        }
      ]
    },
    ...
}
```

This way, if the input language is English, then the brackets will be swapped. Otherwise, the swapping won't happen. If this is the opposite of what you want, then you can replace the `en` with `tr` (I think). I haven't tried this code but I think it's what you want.

**Comment by avatar-lavventura** [comment]
Thanks @thoelze1, it took some time to code it in `json`  but it works. I just added if cases for the `en`.

I share the gist link in case if someone might need it in future: https://gist.github.com/avatar-lavventura/3c6f3b07a08c66a5bfd5222617d2729c
