### ISSUE TITLE
Slight delay after typing a hyper key: possible to eliminate?

### ISSUE THREAD

**Issue by sdondley** [pqrs-org/Karabiner-Elements#2275]
I have been experimenting with using my spacebar as a hyper key. It works well except for a small but perceptible delay when typing normally. I'll tap the space bar once to register a "space" character and it will take a fraction of a second before the cursor advances. It's hardly noticeable but noticeable enough to be annoying.

I toyed with the timeout settings to see if those might help but no luck.

Is there anything that can be done?

**Comment by thoelze1** [comment]
I do the same thing. When I quickly press `space` (for less than `to_if_alone_timeout_milliseconds`), then karabiner-elements posts `space`. If I hold `space` for any longer, then karabiner posts `fn` (which Emacs interprets as "hyper").

The key here is that for karabiner to determine whether I have tapped or held space, it *must* wait for one of the following:

- another key to be pressed while `space` is held, in which case it can be sure that I'm using `space` as `fn`
- a quick release of `space`, in which case it can be sure that I'm using `space` as `space`
- a longer hold of `space`, in which case it can be sure that I'm using `space` as `fn`

In any case, karabiner cannot be *immediately sure* of how I want to use `space`. Therefore, when I tap space, karabiner has to wait for *`space` to be released* to post `space`. The small amount of time between the keyup and keydown, when karabiner elements can't yet be sure, is the delay that you're talking about. So this delay is actually the expected behavior of double mapping `space` to a modifier.

It's annoying at first, but you get used to it and it is well worth it. I found having hyper easily-accessible on the spacebar to be so valuable that I put `shift`, `meta`, `control`, and `super` on the homerow.

**Comment by sdondley** [comment]
That make sense. In other words, Karabiner waits for the space bar to make an `event_up` event before registering it as a key press whereas typically the OS would register a key press as soon as it sees an `event_down` event.

As a workaround, I created a hot key to turn my hyperspace feature on and off with a `tab-o`. `tab-o` will toggle the hyperspace on and off. So when I'm typing fast in here, I turn it off. I built a little indicator in the system menu bar at the top of the screen with BitBar so I know when it's on and off. See https://getbitbar.com
