### ISSUE TITLE
remapping language-specific shortcuts depending on input language

### ISSUE THREAD

**Issue by basbebe** [pqrs-org/Karabiner-Elements#2284]
Hi!

I'm using a german ISO keyboard but am switching back and forth between US and German input languages.

I would like to keep the standard german mapping for "move Focus to next window":
`CMD + <` (the button next to left shift on the ISO keyboard)

I have a working complex modification for that based on input language:
Remap `` CMD + ` `` to `CMD + SHIFT + 'comma'`

What doesn't work though is to cycle *back* since I would use `SHIFT` for that and there can't be two Shifts in a remap I guess?

Are there any common / best practice solutions for this?

**Comment by thoelze1** [comment]
If `CMD` + `<` cycles forward, I'm guessing `CMD` + `>` cycles back? Maybe this is what you want:

- Remap `CMD` + `` ` `` to `CMD` + `SHIFT` + `,`
- Remap `CMD` + `SHIFT` + `` ` `` to `CMD` + `SHIFT` + `.`

**Comment by basbebe** [comment]
sadly it does not.
I guess it's not `CMD` + `>` but `CMD` + `SHIFT` + `<`

**Comment by basbebe** [comment]
so…
Is it possible to map to a specific letter instead of a keypress?
I see no other way of approaching this…

**Comment by zecanard** [comment]
I haven’t been able to find a way. I wish there were.

**Comment by thoelze1** [comment]
I'm still not clear on the use case. Are you looking to use the same finger motion/muscle memory to switch apps regardless of the keyboard (as in `command`+`whatever-key-is-below-your-pinky`)? Or are you looking to use the same character input to switch apps regardless of keyboard (as in `command`+`<`, regardless of where `<` is on the keyboard)?

Looking at the shortcuts on the [German keyboard shortcuts page](https://support.apple.com/de-de/HT201236) I don't see "<" or ">" or "Winkelträger" anywhere - is the `command`+`<` mapping standard for OS X? I should add that I speak very little German and don't use a German keyboard

**Comment by basbebe** [comment]
@thoelze1 it's about using the same key no matter which keyboard layout is activated (at the moment I'm switching between German and us layouts).

The `<` key is on the German ISO Keyboard layout, probably not on the ANSI layout.
It' next to the left shift button.

Even if I changed it to be the ``` backtick key the problem would be the same I guess: when I map it to be somewhere els for the different language mapping, I will only be able to cycle in one direction because the mapping includes a `Shift`.

**Comment by thoelze1** [comment]
It sounds to me like your OS is looking for keyboard shortcuts that are possible in the German layout (but not necessarily in the US layout) _even when you have told your OS that you're using a US keyboard_. Is this correct? It's surprising to me that if you tell macOS that you're using a US layout, that the OS would still be looking for a `<` keypress modified by `command` and `shift` as the system-wide shortcut for move-focus-to-last-window.

A few more questions:

> no matter which keyboard layout is activated

So you're using the same physical keyboard, but you're telling macOS to interpret it according to the German layout sometimes, and according to the US layout other times? How are you "switching" the layout - how are you telling the OS which layout you want to use?

> the same key

Do you mean the same physical key, as in whatever-key-is-next-to-the-left-shift-button or the same character (a <kbd><</kbd> keypress on the German layout is interpreted by the OS to indicate the same character as a <kbd>SHIFT</kbd>+<kbd>,</kbd> keypress on a US layout). 

This seems like a common enough use case that there should be a way to do what you want - so common that I would be surprised if one needed third-party key-remapping software such as karabiner-elements to achieve this behavior.

I keep asking for more info because I'm not familiar with using non-us layouts - but I'm hoping there's a way to do this.

**Comment by basbebe** [comment]
> How are you "switching" the layout - how are you telling the OS which layout you want to use?
Mac OS allows to set the keyboard layout in System preferences and switch by pressing `CTRL + Space`.
I'm using an external ANSI keyboard with US layout and an internal Laptop keyboard with German ISO Layout. I switch between US and german mapping on both of them.


ANSI German:
![Bildschirmfoto 2020-05-25 um 16 45 44](https://user-images.githubusercontent.com/7083188/82823483-f4ae1d80-9ea7-11ea-8669-e8ce6d017c5a.png)

ANSI US: 
![Bildschirmfoto 2020-05-25 um 16 45 47](https://user-images.githubusercontent.com/7083188/82823481-f4158700-9ea7-11ea-9b09-d4944d1845a4.png)

ISO German
![Bildschirmfoto 2020-05-25 um 16 45 37](https://user-images.githubusercontent.com/7083188/82823486-f4ae1d80-9ea7-11ea-92d1-8e8eb0027b45.png)

ISO US
![Bildschirmfoto 2020-05-25 um 16 45 15](https://user-images.githubusercontent.com/7083188/82823488-f546b400-9ea7-11ea-9fe3-0454f0225e16.png)

> Do you mean the same physical key, as in whatever-key-is-next-to-the-left-shift-button or the same character (a < keypress on the German layout is interpreted by the OS to indicate the same character as a SHIFT+, keypress on a US layout).

I would like to be able to press the key next to left shift on ISO keyboards or the key above tab on ANSI keyboards.
But I think Mac OS is looking for characters, not for keys. That's why I don't know how to realize it while retaining the ability to cycle backwards.
Even keeping it on the button above tab no matter the keyboard layout pobably wont't work because of that (?).

**Comment by iamsababa** [comment]
I'm facing the same problem, is it possible to implement this with Karabiner?

**Comment by ariccb** [comment]
I'm facing the same problem, but for my case I'm switching from Qwerty to ColemakDH, not different languages, though they ARE treated as different languages by macOS. I have an external keyboard that uses firmware to remap the keys, so for shortcuts coming from my external keyboard, for example 'alt+f' to open Finder (for ColemakDH F is located at the E location in Qwerty) works great.
But when I am just working on my built-in laptop keyboard, I need to use karabiner-elements to re-map my layout to ColemakDH and I switch from 'ACB - the default Qwerty keyboard layout' to 'ColemakDH` using the language switcher, suddenly my shortcuts are MOVED, so even though my keyboard is typing an F when I hit the qwerty E key (which I want), the SHORTCUTS are treated as if I hit "ALT+E" instead of "ALT+F", so my **E**mail shortcut is activated instead of my **F**inder shortcut. 
So it seems like macOS isn't using the underlying language at all, but it's using the physical hard-coded "E key" location. So when i'm using my ColemakDH layout I still have to press the PHYSICAL F key (which is 'T' in colemakDH) to activate my **F**inder shortcut, which takes away any of the muscle memory I've built.
