### ISSUE TITLE
Help Finding Mouse buttons Keycodes for Logitech MX Master 3 Mouse

### ISSUE THREAD

**Issue by fullmetalsheep** [pqrs-org/Karabiner-Elements#2292]
Hello,

Karabiner Elements is able to recognize the normal mouse buttons such as mouse1, mouse2, mousewheel, and mouse wheel click. But Logitech MX Master 3 has 4 other buttons on the side. I'm just wondering whether anyone was able to get them to be identified with karabiner-elements as native e.g: mouse7,mouse8 etc.. commands?

Thank you.

**Comment by fullmetalsheep** [comment]
Activating extra buttons requires mandatory installation of logitech software as per: 
https://support.logi.com/hc/en-us/articles/360035271133-MX-Master-3-Getting-Started.

Will close this issue now :)

**Comment by ssbarnea** [comment]
Not sure why this is closes because this article clearly does not state the codes for the buttons. I happen to have the same mouse and I was unable to make karabiner to bind "Cmd+0" (reset zoom level on browser) to the middle button.

I do not even have an idea if the middle button is button3 or not, I was not able to find any documentation regarding button codes or how to read them.

**Comment by seanstrom** [comment]
If you're on MacOS there's an app called KeyCodes that logs your key codes, I used it to figure out which key code was being sent for my MX Master 3 thumb button.

Here's the link to the KeyCodes app: https://manytricks.com/keycodes/

**Comment by justinmm2** [comment]
@fullmetalsheep Just set up an M2 Mac Studio w/ Ventura, Karabiner, and my MX Master 3 (non-S). I mapped the side buttons to the default switch desktops shortcuts - they were button4 and button5. I mapped the thumb button to the default Mission Control shortcut. It was registering as left command + tab (🤷‍♂️).

Here are the JSON files I used. Hope they help.

macstudio:complex_modifications justin$ pwd ; cat mxkarabiner45.json 
/Users/justin/.config/karabiner/assets/complex_modifications
{
  "title": "Switch desktop with mouse buttons 4,5",
  "rules": [
    {
      "description": "Maps button 4 to left desktop switch, 5 to right desktop switch",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button4"
          },
          "to": [
            {
              "key_code": "left_arrow",
              "modifiers": "left_control"
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "pointing_button": "button5"
          },
          "to": [
            {
              "key_code": "right_arrow",
              "modifiers": "left_control"
            }
          ]
        }
      ]
    }
  ]
}
macstudio:complex_modifications justin$ cat mxmissioncontrol.json 
    {
        "title": "MX Master Thumb Button to Mission Control",
        "rules": [
            {
                "description": "Remap MX Master thumb button to Mission Control",
                "manipulators": [
                    {
                        "type": "basic",
                        "from": {
                            "key_code": "tab",
                            "modifiers": {
                                "mandatory": [
                                    "left_command"
                                ]
                            }
                        },
                        "to": [
                            {
                                "key_code": "up_arrow",
                                "modifiers": [
                                    "control"
                                ]
                            }
                        ],
                        "conditions": [
                            {
                                "type": "device_if",
                                "identifiers": [
                                    {
                                        "vendor_id": 1133,
                                        "product_id": 45091
                                    }
                                ]
                            }
                        ] 
                    }
                ]
            }
        ]
    }

**Comment by romanr** [comment]
Hw did you do that? To make it detect your buttons? I have MX Master 3 and MX Vertical. Neither "Keycodes" app nor Karabiner's Event Viewer see buttons 4,5. Same in BetterTouchTool. 
I've read all I could find about this and turns out Logitech driver don't expose those buttons to public API.
BeterTocuhTool author wrote that will not reverse engineer protocol because it's not stable method.

Does Karabiner has it reverse engineered?

**Comment by justinmm2** [comment]
@romanr not sure - i think button4/5 always just showed up for me in eventviewer? but if it helps, i can add two things:
1) fairly certain this machine has never had any logitech programs installed on it
2) in eventviewer, if i go to the Devices tab, here's how my mx master 3 appears:

```
    {
        "device_id": 4295082769,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": true,
        "is_pointing_device": true,
        "location_id": 2444856953,
        "manufacturer": "Logitech",
        "product": "MX Master 3",
        "product_id": 45091,
        "serial_number": "463EA1E89BFA7DA9",
        "transport": "Bluetooth Low Energy",
        "vendor_id": 1133
    }
```

**Comment by romanr** [comment]
ohhh I get it.. You're connected with Bluetooth. I am connecting via Logi USB dongle (it was a bit unreliable for me with bluetooth). gotta try bluetooth, thanks!

**Comment by timmybytes** [comment]
If anyone else ends up here trying to remap MX Master 3 keys after upgrading macOS to Sonoma (which seems to entirely break Logi Options+ for configuring the MX Master 3) here's a couple tips, specifically for the "thumb" key remap:

In Karabiner-Elements, make sure you select the device's "modify events" toggle, otherwise key changes you make won't work. 

![Screenshot 2023-10-25 at 9 11 11 AM](https://github.com/pqrs-org/Karabiner-Elements/assets/67444371/4272635c-a1b0-4d10-bee1-fd977747aa94)

For remapping the "thumb" key, I finally got it to work without having to get into the JSON config by selecting the `left_gui`key under "Other".

![Screenshot 2023-10-25 at 9 13 33 AM](https://github.com/pqrs-org/Karabiner-Elements/assets/67444371/126bfc90-bd8e-496a-9489-124cdbd765f5)

**Comment by bransonbowler** [comment]
@timmybytes @justinmm2 @romanr 
would be awesome to figure out how to do this while using the USB dongle rather than bluetooth.. I've noticed that when using the Logi Bolt dongle there are two different devices showing up in karabiner. 

    {
        "device_id": 4295145219,
        "is_game_pad": false,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": true,
        "is_pointing_device": false,
        "location_id": 51642368,
        "manufacturer": "Logitech",
        "product": "USB Receiver",
        "product_id": 50504,
        "transport": "USB",
        "vendor_id": 1133
    }

    {
        "device_id": 4295145215,
        "is_game_pad": false,
        "is_karabiner_virtual_hid_device": false,
        "is_keyboard": false,
        "is_pointing_device": true,
        "location_id": 51642368,
        "manufacturer": "Logitech",
        "product": "USB Receiver",
        "product_id": 50504,
        "transport": "USB",
        "vendor_id": 1133
    }

**Comment by emanumarqu** [comment]
Thanks @justinmm2 and @timmybytes for your replies! Combining insights from both I successfully remapped pressing the gesture button via GUI with two items:

- `Others -> left_gui` mapped to `Media controls -> mission_control`
- `Controls and symbols  #-> tab` mapped to `Disable this key -> vk_none`
