### ISSUE TITLE
How to lock a key with karabiner?

### ISSUE THREAD

**Issue by eret9616** [pqrs-org/Karabiner-Elements#2318]
I was using a software, in some situation, I need to hold control for a very long time,

so I want :

long-press control for 1second  the control is locked to key-down state,

then retap control to cancel that state, 

is there any way to achieve this with karabiner?

**Comment by haakonstorm** [comment]
I don't know exactly, but you could use `cliclick` from `homebrew` and just send `control` `key down` and then `control` `key up` when done.

**Comment by nkgm** [comment]
Does `cliclick kd:ctrl` work or you @haakonstorm? In my case it doesn't set the modifier for subsequent keys.

**Comment by haakonstorm** [comment]
Perhaps `cliclick` only respects `kd:ctrl` for subsequent keypresses only dispatched from `cliclick` itself.
What you could do, and I have this on my to-do list to do when time, is to map every key on the keyboard in karabiner, so that every keypress is sent to a `named pipe` which is `read` by a daemonized zsh script or Go binary where you implement such stateful logic. I haven't gone too far in checking out the viability of this solution, but if it works, it'll be glorious.

Also, if you haven't seen it, there is another utility for faster and more flexible creation of karabiner configurations - https://github.com/yqrashawn/GokuRakuJoudo.

[Here](https://medium.com/@nikitavoloboev/karabiner-god-mode-7407a5ddc8f6) is a nice writeup by @NikitaVoloboev with lots of how-tos to start implementing what you want.

**Comment by nkgm** [comment]
> Perhaps cliclick only respects kd:ctrl for subsequent keypresses only dispatched from cliclick itself.

It only respects the keydown's within the same invocation, ie `cliclick kd:ctrl kp:arrow-up` works. But if you were to split that up into separate invocations then it doesn't work.

> a daemonized zsh script or Go binary where you implement such stateful logic. I haven't gone too far in checking out the viability of this solution, but if it works, it'll be glorious.

I'm doing something similar with hammerspoon and while it sort of works, it's not nearly as reliable as karabiner. Besides, if you're willing to put in the work, you might as well fork karabiner and implement the desired functionality yourself, even though I feel we might see this feature in the future as @tekezo has repeatedly shown he's striving for feature parity with the good old karabiner.

> Also, if you haven't seen it, there is another utility for faster and more flexible creation of karabiner configurations

That is very impressive, definitely something to look at. At the moment I'm generating my `karabiner.json` with a simple nodejs project that helps me abstract away the very repetitive elements. Seeing it's so trivial to move between javascript objects and JSON, it feels like a natural match, and has no external dependencies other than `lodash`.

**Comment by haakonstorm** [comment]
@nkgm Did you try running `cliclick` in a daemonized script, or start it with a key down, then a LONG `wait` before a key up?

**Comment by nkgm** [comment]
@haakonstorm not sure how it would help my current setup, or how to go about it. Can you give me an example?
