### ISSUE TITLE
No karabiner_grabber etc. in System Preferences

### ISSUE THREAD

**Issue by yannis1962** [pqrs-org/Karabiner-Elements#2356]
When starting Karabiner-Elements for the first time I'm asked to add karabiner_grabber and karabiner_observer to "Input Monitoring" in System Preferences. But in my System Preferences that entry is called "Surveillance de l'entrée" and there is no karabiner_grabber and no karabiner_observer. And as I don't where these are located I cannot add them manually either. Could you please fix that?
<img width="1665" alt="2020-07-16_18-54-29" src="https://user-images.githubusercontent.com/749949/87700245-5434f500-c796-11ea-8566-f57c612edbef.png">

**Comment by steshaw** [comment]
I have this problem as well. I installed Karabiner-Elements via Homebrew Cask formula `karabiner-elements`. I'm on macOS Catalina 10.15.6 (19G73).

**Comment by TheRealWaldo** [comment]
Also have the same issue with a larger impact:

With a sym linked configuration folder that lives under the Documents folder, this prevents the application from functioning at all.

The only work-around is to grant karabiner_grabber Full Disk Access, which is of course a nasty security issue.

**Comment by steshaw** [comment]
KE started working for me mysteriously. It was possibility because KE upgraded me from 12.9.0 ([which I'd downgraded to](https://github.com/pqrs-org/Karabiner-Elements/issues/2356#issuecomment-664999891)) to 12.10.0. I may have rebooted. At some point KE notified me give permission to karabiner_grabber and karabiner_observer in System Preferences and they were there and it worked.

My internal keyboard now shows in in the Devices tab. There is another unenabled keyboard that is a mystery to me (possible a Bluetooth keyboard I have that I no longer use).

![image](https://user-images.githubusercontent.com/45735/89697551-f42e0a80-d95f-11ea-9087-5d0e250c85b5.png)

So, I suggest:

1. Downgrade to [12.9.0 from the GitHub releases](https://github.com/pqrs-org/Karabiner-Elements/releases/tag/v12.9.0).
2. Allow KE to self-update to 12.10.0.
3. Reboot once or twice.

**Comment by coodoo** [comment]
I ran into this issue today, Catalina 10.15.6, ended up **one must restart the computer** to make both grabber and observer working, once rebooted, internal keyboard will be detected and imported complex modifications started working.

**Comment by steshaw** [comment]
You were lucky, @coodoo. I tried rebooting (several times), after installing KE 12.10.0 the first time via Homebrew Cask. It didn't help with karabiner_grabber and karabiner_observer, nor with having the internal keyboard turn up in Devices. Perhaps you didn't install from Homebrew Cask? That could be broken.

**Comment by coodoo** [comment]
@steshaw Yup, I manually downloaded and installed it, probably that's why it worked? 🤷‍♂️
