### ISSUE TITLE
Modifiers with additional mouse buttons

### ISSUE THREAD

**Issue by kozubikmichal** [pqrs-org/Karabiner-Elements#2382]
Hi,

I'd like to map for example shift+mouse button 4 to some other key (eg. num 1), a created this rule but it is not working. Any idea whats the issue?

```json
{
	"title": "Mouse Buttons Modifiers",
	"rules": [{
		"description": "Shift + Mouse buttons",
		"manipulators": [{
			"type": "basic",
			"from": {
				"pointing_button": "button4",
				"modifiers": {
					"mandatory": ["left_shift"],
					"optional": ["caps_lock"]
				}
			},
			"to": [{
				"key_code": "keypad_1"
			}]
		}]
	}]
}
```

**Comment by kozubikmichal** [comment]
I tried that with both shifts but with no success. Button4 is working OK - by default I have enabled simple modifications to use button4 as a volume_decrement and button5 as a volumne_increment. This is working fine. Also doing this as a complex modification is working, but the modifier key is ignored

**Comment by MuhammedZakir** [comment]
I am using Mojave and it is working fine for me! Are you trying to do this complex modification along with simple modifications (volume increment/decrement)? Also, make sure there is only this rule for button4 in `karabiner.json` before trying. Or this is because of your OS? Are you perhaps using Catalina?

**Comment by kozubikmichal** [comment]
While trying those complex modifications I disabled all simple modifications to ensure there are not conflicts.
Yes, I am using Catalina (10.15.6). Are there compatibility issues with this version?

**Comment by MuhammedZakir** [comment]
> Yes, I am using Catalina (10.15.6). Are there compatibility issues with this version?

Many users have reported issues with KE in Catalina and Big Sur. It's a work in progress now. You will have to wait for the new update.

**Comment by jonhoo** [comment]
For what it's worth, I'm also encountering this same issue on Catalina (10.15.7) and KE 13.1.0. I'm trying to map `control` + `button3` to `control` + `left_arrow` (and same for `button4` + `right_arrow`). I don't think any of the settings for the device are wrong, because mapping _just_ `button3` to `control` + `left_arrow` works just fine.

**Comment by kozubikmichal** [comment]
I can confirm that after last update this case is working fine on Big Sur.

Thanks!

**Comment by laxman-stan** [comment]
> For what it's worth, I'm also encountering this same issue on Catalina (10.15.7) and KE 13.1.0. I'm trying to map `control` + `button3` to `control` + `left_arrow` (and same for `button4` + `right_arrow`). I don't think any of the settings for the device are wrong, because mapping _just_ `button3` to `control` + `left_arrow` works just fine. I did not have any optional modifiers. This smells like a re-surfacing of #2119.

Hi @jonhoo did it work 
and if yes
could you please share the config.

**Comment by jonhoo** [comment]
I no longer have the computer where I experienced this, which also means I don't have the config any more. Sorry!
