### ISSUE TITLE
Option to treat mouse buttons like modifiers

### ISSUE THREAD

**Issue by jeffomatic** [pqrs-org/Karabiner-Elements#2417]
This is a feature request for adding the ability to get modifier-like behavior for mouse buttons. In other words, I would like to use mouse buttons in a similar fashion to they way you would use `shift`/`control`/etc. The goal isn't to re-map a mouse button directly to a pre-existing modifier, but to allow the mouse button to be held down in order to modify one or more future input events.

In particular, I wonder if it might be possible to upgrade Karabiner to put _any_ key or button ID into the `modifiers` property. I would be happy to explore writing a patch for this, but I'd like to gut-check the idea with the project community first. Thanks in advance!

Here's an example use case. I'm a big fan of the Evoluent Vertical mouse, which has six buttons. The manufacturer's driver lets you hold the thumb button (`button6`) while clicking other mouse buttons to generate different OS effects. I use this to switch to the next or previous Mac OS desktop. In practice, I often find myself holding down `button6` while switching back and forth between desktops multiple times. You can think of this as treating a mouse button almost like a layer selector (e.g., `fn`) on a programmable keyboard.

So far, Evoluent has been unable to release a driver for Catalina, which makes me very pessimistic about their ability to produce a driver for Big Sur as well. So, I've tried emulating this using Karabiner's complex modifier system with a `simultaneous` specification. Here's one example:

```
{
  "description": "Lower button + left click: go right one space",
  "parameters": {
    "basic.simultaneous_threshold_milliseconds": 500
  },
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "simultaneous": [
          {
            "pointing_button": "button6"
          },
          {
            "pointing_button": "button1"
          }
        ],
        "simultaneous_options": {
          "key_down_order": "strict",
          "key_up_when": "any"
        }
      },
      "to": {
        "key_code": "right_arrow",
        "modifiers": [
          "left_control"
        ]
      }
    }
  ]
}
```

This works okay, but suffers from a couple of problems:

- In order to produce the same result _twice_, you have to let go of `button6` and press it down again.
- It's noticeably harder to execute than if I could just hold down `button6` indefinitely, and click `button1` an arbitrary number of times, at an arbitrary point in time. I get a lot of "false negatives" where I think I'm executing this button chord, but nothing happens, or a get a regular single click.

**Comment by MuhammedZakir** [comment]
I don't think we should add "fake" modifier keys to default modifiers. You can use `variable if/unless` conditions to create your own modifier keys instead [1].

[1] https://karabiner-elements.pqrs.org/docs/json/extra/virtual-modifier/

https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/ **:**
> **Note**
> The following keys are exclusive.
> You cannot specify multiple items into one to entry.
>
> * `key_code`
> * `consumer_key_code`
> * `pointing_button`
> * `shell_command`
> * `select_input_source`
> * `set_variable`
> * `mouse_key`

Sample config:
```json
{
  "title": "Mouse button as modifier",
  "rules": [{
    "description": "Mouse button as modifier",
    "manipulators": [
      {
        "type": "basic",
        "from": {
          "pointing_button": "button2",
          "modifiers": {
            "optional": ["caps_lock"]
          }
        },
        "parameters": {
          "basic.to_if_alone_timeout_milliseconds": 700
        },
        "to_if_alone": [{
          "pointing_button": "button2"
        }],
        "to": [{
          "set_variable": {
            "name": "mouse button2 modifier",
            "value": 1
          }
        }],
        "to_after_key_up": [{
          "set_variable": {
            "name": "mouse button2 modifier",
            "value": 0
          }
        }]
      },
      {
        "type": "basic",
        "from": {
          "pointing_button": "button1",
          "modifiers": {
            "optional": ["caps_lock"]
          }
        },
        "conditions": [{
          "type": "variable_if",
          "name": "mouse button2 modifier",
          "value": 1

        }],
        "to": [{
          "key_code": "right_arrow",
          "modifiers": ["control"]
        }]
      }
    ]
  }]
}
```

Note: I added `set_variable` in `to` rather than `to_if_held_down` because latter is different from what you want to achieve. If `to_if_held_down` is used, variable will be set "after" holding the button for X milliseconds [2]. Whereas, `to` will set it immediately, creating a "modifier key" the moment you hold the button, just like a normal mouse.

`to_if_alone`: As long you don't press any other key within X milliseconds [3], this event will be send. This can be used as a "buffer period".

[2] You can change it in `parameters.basic.to_if_held_down_threshold_milliseconds` - https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-held-down/.
[3] `parameters.basic.to_if_alone_timeout_milliseconds`

**Comment by jeffomatic** [comment]
@MuhammedZakir Thank you very much for such a detailed suggestion and all of the references. Using your example as a guide, I was able to achieve the effect I wanted!

I do have one question about the concept of modifiers. You mention a notion of "fake modifiers". I am curious what makes any key/button more "fake" than ctrl/shift/etc. While the latter are conventionally used in chords/combinations, I think of them as fundamentally the same thing as other keys. But perhaps Karabiner has some special handling of the latter? Wouldn't it be architecturally simpler to treat every key and button in the same way?

**Comment by MuhammedZakir** [comment]
> @MuhammedZakir Thank you very much for such a detailed suggestion and all of the references. Using your example as a guide, I was able to achieve the effect I wanted!

You're welcome! :-)

> I do have one question about the concept of modifiers. You mention a notion of "fake modifiers". I am curious what makes any key/button more "fake" than ctrl/shift/etc.

Control/Alt/Command/Shift/Caps-lock/Fn - generally, all these keys are *always* used as modifiers in *all* keyboards. And when we talk about modifier keys, we usually mean these. Another reason is that using them alone do nothing, even a combination of multiple modifier keys do nothing; you will always have to use it with a "non-modifier" keys for anything useful. However, that's not the case with "non-modifier" keys, they can be used alone, and also, they are repeated if held down. So to make them distinct from other keys, I used "fake modifier" for non-modifier keys. Note that this is **just** my personal opinion. Others may or may not agree with this.

But I guess "fake" was a bad choice, huh?

>  While the latter are conventionally used in chords/combinations, I think of them as fundamentally the same thing as other keys.

To be frank, all those things I mentioned earlier can be considered software-related [1]. Technically, we can use all these keys as modifiers. I said not to add other keys to default modifiers because different people use different keys as modifiers. For example, in your case, a mouse button. Some use `escape`, some use `space`, some use `caps-lock`, etc. So if one key is added to default modifiers, some would want another, some another, and this would go on. This will become a mess. **Of course, we can solve this by making it possible to use *any* key as modifier. This can simplify complex modification, as we won't need to use variable condition**. 😁 I am not sure if this will create any unnecessary complication for developers though.

[1] https://askubuntu.com/a/19565

> But perhaps Karabiner has some special handling of the latter? Wouldn't it be architecturally simpler to treat every key and button in the same way?

I don't know how Karabiner handles them, or any other keys for that matter.
