### ISSUE TITLE
Modifications don't seem to work with Keychron Q3 keyboard

### ISSUE THREAD

**Issue by attaboy** [pqrs-org/Karabiner-Elements#3065]
macOS version: macOS 12.1
Karabiner version: 14.4.0
Mac: 14" MacBook Pro 2021 (M1 Pro)
Keyboard: Keychron Q3

When I try to do simple modifications, they have no effect on my Keychron Q3 keyboard. It's a recently-released model, but I have previously used Karabiner with a Keychron Q1.

A simple modification like mapping "a" to "b" causes the expected behavior on my MacBook Pro's internal keyboard, but no change on the Keychron Q3.

**Comment by whkoh** [comment]
+1 I'm seeing this too

**Comment by MuhammedZakir** [comment]
Can you post a screenshot of Karabiner-Elements preferences > Devices?

**Comment by attaboy** [comment]
@MuhammedZakir Ah hah! In doing this, I noticed that the keyboard appears twice on that list, and only one of the items was checked. When I checked the unchecked one, Karabiner started working as expected. By default, only the second of these two entries (the one listed as keyboard only) were checked for some reason:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/71433/163828436-e0810eac-f974-42f8-9498-1305b9866329.png">

**Comment by MuhammedZakir** [comment]
Yeah, this can happen. That's why I asked for a screenshot.

> By default, only the second of these two entries (the one listed as keyboard only) was checked for some reason.

IIRC, KE doesn't modify mouse events by default. You'll have to explicitly enable them. That's what happening here.

> The confusing thing is that the EventViewer was showing all events from the keyboard, so I assumed it was being recognized correctly.

You can think of EventViewer as a key logger when it comes to key events. It monitors all events of certain types (mouse, keyboard, etc.) and then displays whatever it gets. You can use it even if KE is not running. For examle, to test some other low-level remapping tools/extensions. Also, it is not probably hard to extend EventViewer to monitor other events [1].

[1] https://developer.apple.com/documentation/hiddriverkit/hid_usage_tables

**Comment by tborychowski** [comment]
Just to add a note to the issue: selecting all variations of the keyboard in Devices also fixed it for me.
However: the weird thing is that I also have an older Keychron K8, and I have only 1 option checked in Devices, and modifications worked for K8 no problem. For Q3 I had to tick all variations (keyboard and keyboard+mouse).

Anyways, all fine now, thanks :-)
