### ISSUE TITLE
Bug? `set_variable` only works with integer as value

### ISSUE THREAD

**Issue by chrisgrieser** [pqrs-org/Karabiner-Elements#3091]
It took me a while to figure this out, cause I could not make `set_variable` work, until a looked at other modifications and noticed they were all using integers as values. The docs, however, not only do not indicate this requirement, but even suggest a string in the example, which is in fact not working.

So either the docs are erroneous, or there is a bug that I cannot set variables to a non-integer value. (I tried string & boolean.)

**Comment by MuhammedZakir** [comment]
I/we have always used integers for variable's value. So it's highly likely the doc that's wrong.

What does the log say when you use a string? See Log tab.

**Comment by chrisgrieser** [comment]
Guess in that case, the docs really need to be updated. the example showing a string really misled me. https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/set-variable/

<img width="679" alt="Pasted image 2022-05-20 14 46 05" src="https://user-images.githubusercontent.com/73286100/169530928-7c42e5e1-1770-40ac-964d-d749663422d4.png">

**Comment by tekezo** [comment]
Thank you for feedback!

The string and boolean value are available with `set_variable` since the latest beta version (v14.4.20)

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)
