### ISSUE TITLE
Disable Built-in Keyboard not Working

### ISSUE THREAD

**Issue by micwaab** [pqrs-org/Karabiner-Elements#3094]
Karabiner "Disable the built-in keyboard when external keyboard is connected" feature stopped working today. I've been using this feature for a year without issue, but today it stopped working.

**Comment by ruolis** [comment]
I have the same problem

macOS：12.3.1
Karabiner-Elements：14.4.0

**Comment by xbladesub** [comment]
doesn't work with ZMK controllers.
macOS 12.6, karabiner - 14.10.0

**Comment by jovyllebermudez** [comment]
and me my issue is, i want to know why karabiner disables the built in keyboard. can you guys give me a hint?

**Comment by gin419** [comment]
> and me my issue is, i want to know why karabiner disables the built in keyboard. can you guys give me a hint?

I have the same issue and also need this feature much.

I have the MBP 2017 and the internal keyboard is suck, since I replace it 2 times it still bad, some key will stack and hard to use. that's why i use the another keyboard - Nuphy Air 75 - which can place on the internal keyboard and fit perfectly. In case I need disable the internal keyboard or my new keyboard will push the internal keyboard keys.

I am thinking this feature is great for many MacOS user who use the MBP with butterfly keyboard heavily.

My system: MacOS 13.2, Karabiner: 14.11.0
