### ISSUE TITLE
Add "Unknown Events"? (Mi Box S bluetooth remote)

### ISSUE THREAD

**Issue by adriel** [pqrs-org/Karabiner-Elements#3098]
I'm trying to use an old [Mi Box S remote](https://www.dignited.com/66181/xiaomi-mi-box-s-review-android-tv-on-any-tv-for-a-decent-price/), most of the keys are already recognised in Karabiner-Elements, it's only missing the arrow + centre buttons and the prime button events.

These missing buttons do show up in the Unknown Events in the Karabiner-EventViewer app though, so I'm hopfull they can be added one day? (or is it something I can do in the app)

"Prime video" button
```
value:1              HID usage: 12,108   
value:0              HID usage: 12,108   
```

Left, up, right, down
```
value:1              HID usage: 12,68    
value:0              HID usage: 12,68    
value:1              HID usage: 12,66    
value:0              HID usage: 12,66    
value:1              HID usage: 12,69    
value:0              HID usage: 12,69    
value:1              HID usage: 12,67    
value:0              HID usage: 12,67  
```

Center button (enter)
```
value:1              HID usage: 12,65    
value:0              HID usage: 12,65      
```

**Comment by tekezo** [comment]
The remote control buttons are available since the latest beta version.

<img width="1087" alt="Screen Shot 2022-08-14 at 10 45 53" src="https://user-images.githubusercontent.com/659178/184519796-33f10f67-27b8-4397-80b6-670e4cd545e7.png">


How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by adriel** [comment]
@tekezo This is HUGE news! This will be so helpful, thank you!!

I just gave it a try, and all the buttons are now recognised (after updating).

**Comment by tekezo** [comment]
Thank you for confirmation!
