### ISSUE TITLE
Complex Modifications not working on macOS Ventura

### ISSUE THREAD

**Issue by Auratelience** [pqrs-org/Karabiner-Elements#3116]
After updating to macOS Ventura Developer Beta 1 (22A5266r), complex modifications are no longer working. Simple modifications were originally not working either but deleting and remaking them fixed it.
Thanks in advance, Auratelience.

**Comment by ctrlok** [comment]
Somehow it starts to work after enabling and then disabling "Caps lock as hyper key" in BetterTouchTool. Only works for an hour or so, then need to enable and then disable "Caps lock as hyper key" in BTT again.

**Comment by MuhammedZakir** [comment]
It is probably a bug in macOS Ventura Beta. For a related example, see https://github.com/noah-nuebling/mac-mouse-fix/issues/297.

**Comment by ctrlok** [comment]
btw, I found that problem was in security settings which blocks extension from loading. Reenable extension in 

System Settings → General → Login Items 
(enable just everything) 

then reboot and allow extension to load via 
System Settings → Privacy and security → There will be a question under security 

then reboot again. 
Everything works for me again.

**Comment by Auratelience** [comment]
@ctrlok, I enabled some things which were just labelled with people's names and that seemed to work. If we could get a list, or have the names related to KE it would be ideal.
