### ISSUE TITLE
Help --> The virtual keyboard and mouse driver is not loaded in MacOS Ventura

### ISSUE THREAD

**Issue by mochiware** [pqrs-org/Karabiner-Elements#3268]
First thank you KE developers for a great product and the community for your help.

I just upgraded to MacOS Ventura from Monterey. KE 14.10.0 was working fine under Monterey. Now under Ventura, I get the "The virtual keyboard and mouse driver is not loaded error". What am I doing wrong? I've tried the following

1. I followed the prompts from the screenshots below where I "Deactivate driver", restart, activate then click "Allow" on Security and Preferences which then shows driver successfully activated and the "Allow" button goes away. But KE still doesn't work. I quit KE and launch KE and the same prompts pops up again.
2. So then I tried uninstalling KE, restarting MacOS and then reinstalling KE but then it goes back to the 1. above. 

![Screenshot 2022-10-25 at 3 59 10 PM](https://user-images.githubusercontent.com/11140657/197720328-4620d647-b14d-4a6b-8443-ce132f642f23.jpg)

![Screenshot 2022-10-25 at 4 41 33 PM](https://user-images.githubusercontent.com/11140657/197727892-37f67839-b08b-4cc2-ae93-95eaaabee18a.jpg)

**Comment by mochiware** [comment]
Maybe this will help someone else. I went ahead and reinstall macOS Monterey then upgraded to Ventura and KE installed without any problems. Might have been some residual legacy bloatware.

**Comment by Gq77** [comment]
My issue on Ventura coming from Monterey that works flawless... is that when on installing on the recovery window, does not allow to proceed,  as it keeps looking for mouse and keyboard.  When updating I use plugged mouse and keyboard.  The wireless keyboard I don't unless already updated.   Why does it do this?  Is it because the drivers need to be updated prior to running the update via flash-drive USB? OCLP?

**Comment by Gq77** [comment]
Where do we find the VENTURA keyboard mouse and trackpad so we can install them before updating?  APPLE does not seem to want anyone to have them.  Just curious.
