### ISSUE TITLE
[Feature request] clone profiles

### ISSUE THREAD

**Issue by Marx1st** [pqrs-org/Karabiner-Elements#3319]
I use karabine mostly to remap input devices for games (eg Razer Nostromo). This can be pretty tedious, as one has to create new profiles for every game one wants to change key bindings for. 
A function to clone existing profiles would be VERY helpfull here!

**Comment by nejmeijer** [comment]
This is already possible by manually copying the corresponding block of lines in the file `~/.config/karabiner/karabiner.json` in a text editor. (`...` stands for omitted code)
```
    "profiles": [
        {
            ...

            "name": "Default profile",

            ...
        },
        {
            ...

            "name": "Default profile I copied",

            ...
        },
        {
            ...

            "name": "Other profile",

            ...
        }
    ]
```
Make sure to back the file up first, because it is _extremely_ easy to break it with e.g. a single missing comma. Documentation can be found [here](https://karabiner-elements.pqrs.org/docs/json/).
