### ISSUE TITLE
Background items list shows developer account

### ISSUE THREAD

**Issue by r357** [pqrs-org/Karabiner-Elements#3355]
Hi, with today's update, I noticed "Fumihiko Takayama" in the system settings/general/login items/allow in the background:
![image](https://user-images.githubusercontent.com/32488308/211144790-1880d79f-396d-42e5-8253-d60f822137c2.png)
I understand this is because @tekezo is probably the developer signing this app, but is this something you should know about?

Just a thought, not a real issue.
Thank you for putting in all the good work on this project!

**Comment by tekezo** [comment]
Thank you for your report. Basically, there is no problem if you leave it as it is.

It is a problem on the macOS side, and I tried to work around it as much as I could, hoping it would never happen, but it didn't...

If you have built Karabiner-Elements from source code, this issue is likely to occur.
Otherwise, restarting macOS will most likely normalize the display name.

I have written more information on the following page:
https://karabiner-elements.pqrs.org/docs/help/troubleshooting/fumihiko-takayama-in-login-items/
