### ISSUE TITLE
Add Command + S (Save) shortcut to rule/json editor

### ISSUE THREAD

**Issue by hyuri** [pqrs-org/Karabiner-Elements#3938]
Currently, Command + S in the rule/json editor does not save the file. We are forced to use the mouse/trackpad to press the Save button in the corner.

It would be helpful if we could simply press Command + S to save, like it is supported in other apps.

**Comment by tekezo** [comment]
Indeed, that's correct. In the latest beta version (v15.0.16), I made it so that pressing command+s performs the same action as clicking the save button.
Having the window close has its pros and cons, but for now, I'll go with this behavior.


How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by hyuri** [comment]
Awesome! Thank you!
